SELECT 
    MARKET,
    LOAD_SHAPE,
    PRODUCT,
    PRICE_TYPE,
    PRICE,
    PUBLICATION_DATE
FROM FLK_DUB_DB_DATALAKE_PRD.STAGING_WMS_EDFT.POWER
WHERE PUBLICATION_DATE = CURRENT_DATE() - 6
  AND MARKET = 'UNITED KINGDOM'
  AND PRICE_TYPE = 'MID'
  AND PRODUCT = '20250622';
